package com.ufes.acessousuarios.view;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public MainView() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        btnNotificacoes = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        nameUsuario = new javax.swing.JLabel();
        tipoUsuario = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuUsuarios = new javax.swing.JMenu();
        menuBuscar = new javax.swing.JMenuItem();
        menuCadastrar = new javax.swing.JMenuItem();
        menuOpcoes = new javax.swing.JMenu();
        menuLog = new javax.swing.JMenuItem();
        menuAlterarSenhar = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNotificacoes.setText("Notificações");

        jLabelUsuario.setText("Usuario : ");

        jLabelTipo.setText("Tipo :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoUsuario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameUsuario)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addComponent(btnNotificacoes)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUsuario)
                    .addComponent(nameUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipo)
                    .addComponent(tipoUsuario))
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnNotificacoes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        desktopPane.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                .addGap(0, 174, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuUsuarios.setText("Usuários");

        menuBuscar.setText("Buscar");
        menuUsuarios.add(menuBuscar);

        menuCadastrar.setText("Cadastrar");
        menuUsuarios.add(menuCadastrar);

        barraMenu.add(menuUsuarios);

        menuOpcoes.setText("Opções");

        menuLog.setText("Log");
        menuOpcoes.add(menuLog);

        menuAlterarSenhar.setText("Alterar senha");
        menuOpcoes.add(menuAlterarSenhar);

        menuSair.setText("Sair");
        menuOpcoes.add(menuSair);

        barraMenu.add(menuOpcoes);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JDesktopPane getDesktopPane() {
        return desktopPane;
    }

    public JMenuItem getMenuBuscar() {
        return menuBuscar;
    }

    public JMenuItem getMenuCadastrar() {
        return menuCadastrar;
    }

    public JMenuItem getMenuLog() {
        return menuLog;
    }

    public JMenuItem getMenuSair() {
        return menuSair;
    }

    public JMenuBar getBarraMenu() {
        return barraMenu;
    }

    public JMenu getMenuOpcoes() {
        return menuOpcoes;
    }

    public JMenu getMenuUsuarios() {
        return menuUsuarios;
    }

    public JButton getBtnNotificacoes() {
        return btnNotificacoes;
    }

    public void setBtnNotificacoes(JButton btnNotificacoes) {
        this.btnNotificacoes = btnNotificacoes;
    }

    public JLabel getNameUsuario() {
        return nameUsuario;
    }

    public void setNameUsuario(JLabel nameUsuario) {
        this.nameUsuario = nameUsuario;
    }

    public JLabel getTipoUsuario() {
        return tipoUsuario;
    }

    public void setTipoUsuario(JLabel tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }

    public JLabel getjLabelTipo() {
        return jLabelTipo;
    }

    public JLabel getjLabelUsuario() {
        return jLabelUsuario;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JMenuItem getMenuAlterarSenhar() {
        return menuAlterarSenhar;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton btnNotificacoes;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuAlterarSenhar;
    private javax.swing.JMenuItem menuBuscar;
    private javax.swing.JMenuItem menuCadastrar;
    private javax.swing.JMenuItem menuLog;
    private javax.swing.JMenu menuOpcoes;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenu menuUsuarios;
    private javax.swing.JLabel nameUsuario;
    private javax.swing.JLabel tipoUsuario;
    // End of variables declaration//GEN-END:variables
}
