package com.ufes.acessousuarios.view;

import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public MainView() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        barraMenu = new javax.swing.JMenuBar();
        menuUsuarios = new javax.swing.JMenu();
        menuBuscar = new javax.swing.JMenuItem();
        menuCadastrar = new javax.swing.JMenuItem();
        menuOpcoes = new javax.swing.JMenu();
        menuLog = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        menuUsuarios.setText("Usuários");

        menuBuscar.setText("Buscar");
        menuUsuarios.add(menuBuscar);

        menuCadastrar.setText("Cadastrar");
        menuUsuarios.add(menuCadastrar);

        barraMenu.add(menuUsuarios);

        menuOpcoes.setText("Opções");

        menuLog.setText("Log");
        menuOpcoes.add(menuLog);

        menuSair.setText("Sair");
        menuOpcoes.add(menuSair);

        barraMenu.add(menuOpcoes);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JDesktopPane getDesktopPane() {
        return desktopPane;
    }

    public JMenuItem getMenuBuscar() {
        return menuBuscar;
    }

    public JMenuItem getMenuCadastrar() {
        return menuCadastrar;
    }

    public JMenuItem getMenuLog() {
        return menuLog;
    }

    public JMenuItem getMenuSair() {
        return menuSair;
    }

    public JMenuBar getBarraMenu() {
        return barraMenu;
    }

    public JMenu getMenuOpcoes() {
        return menuOpcoes;
    }

    public JMenu getMenuUsuarios() {
        return menuUsuarios;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem menuBuscar;
    private javax.swing.JMenuItem menuCadastrar;
    private javax.swing.JMenuItem menuLog;
    private javax.swing.JMenu menuOpcoes;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenu menuUsuarios;
    // End of variables declaration//GEN-END:variables
}
